server:
  port: 8009
spring:
  application:
    name: service-acl
  profiles:
    active: dev
  cloud:
    # nacos服务地址
    nacos:
      discovery:
        server-addr: localhost:8848
    #服务容错
    sentinel:
      transport:
        port: 8081
        dashboard: loclhost:8080
  # mysql数据库连接
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver #驱动类名
    url: jdbc:mysql://localhost:3306/edu_acl?serverTimezone=GMT%2B8
    username: education
    password: wyzxgzsLZH1
  #返回json的全局时间格式
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  redis:
    host: localhost
    port: 6379
    database: 0
    timeout: 1800000
    lettuce:
      # 连接池
      pool:
        max-active: 20
        #最大阻塞等待时间(负数表示没限制)
        max-wait: -1
        max-idle: 5
        #最小空闲
        min-idle: 0
#配置mapper xml文件的路径
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #mybatis日志
  mapper-locations: classpath:com/prestrive/com/service/acl/mapper/xml/*

ribbon:
  ConnectTimeout: 10000 #连接建立的超时时长，默认1秒
  ReadTimeout: 10000 #处理请求的超时时间，默认为1秒

#开启Feign对Sentinel的支持
feign:
  sentinel:
    enabled: true