server:
  port: 8150
spring:
  application:
    name: service-sms # 服务名
  profiles:
    active: dev # 环境设置
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 # nacos服务地址
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    lettuce:
      pool:
        min-idle: 0     #最小空闲连接，默认0
        max-idle: 8     #最大空闲连接，默认8
        max-wait: -1    #最大阻塞等待时间，负值表示没限制，默认-1
        max-active: 20  #最大连接数，负值表示没有限制，默认8
