server:
  port: 8130
spring:
  profiles:
    active: dev # 环境设置
  application:
    name: service-vod # 服务名
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 # nacos服务地址
  servlet:
    multipart:
      max-request-size: 5MB # 最大上传单个文件大小：默认1M
      max-file-size: 5MB # 最大置总上传的数据大小 ：默认10M
