server:
  port: 8110 # 服务端口
  tomcat:
    max-threads: 10 #tomcat的最大并发值修改为10,默认是200

spring:
  profiles:
    active: dev # 环境设置
  application:
    name: service-edu # 服务名
  datasource: # mysql数据库连接
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/education?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: education
    password: wyzxgzsLZH1

  #spring:
  jackson: #返回json的全局时间格式
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  #spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 # nacos服务地址
    sentinel:
      transport:
        port: 8081 #跟控制台交流的端口，随意指定一个未使用的端口即可
        dashboard: localhost:8080 # 指定控制台服务的地址
  # redis 连接池 配置
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    #password: 123456
    lettuce:
      pool:
        max-active: 20 #最大连接数，负值表示没有限制，默认8
        max-wait: -1    #最大阻塞等待时间，负值表示没限制，默认-1
        max-idle: 8 #最大空闲连接，默认8
        min-idle: 0 #最小空闲连接，默认0


#mybatis日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#  #mapper实现的位置
  mapper-locations: classpath:/mapper/mapper/*Mapper.xml
  type-aliases-package: com.prestrive.com.service.*.entity
# 设置日志级别
#logging:
#  level:
#    root: INFO

#配置负载均衡策略
service-oss: # 调用的提供者的名称
  ribbon:
    #策略名
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule #随机策略

#ribbon服务调用重试规则
ribbon:
  MaxAutoRetries: 0 # 同一实例最大重试次数，不包括首次调用，默认0
  MaxAutoRetriesNextServer: 1 # 重试其他实例的最大重试次数，不包括首次所选的server，默认1
  ConnectTimeout: 10000 #连接建立的超时时长，默认1秒
  ReadTimeout: 10000 #处理请求的超时时间，默认为1秒

#开启Feign对Sentinel的支持
feign:
  sentinel:
    enabled: true

