server:
  port: 9110 # 服务端口
spring:
  profiles:
    active: dev # 环境设置
  application:
    name: infrastructure-apigateway # 服务名
  cloud:
    gateway:
      routes:
      - id: service-edu
        uri: lb://service-edu #lb：表示在集群环境下通过负载均衡的方式调用
        predicates:
          - Path=/user/**,/*/edu/** # 一个*代表一个占位符，**代表多个
      - id: service-cms
        uri: lb://service-cms
        predicates:
          - Path=/*/cms/**
      - id: service-oss
        uri: lb://service-oss
        predicates:
          - Path=/*/oss/**
      - id: service-sms
        uri: lb://service-sms
        predicates:
          - Path=/*/sms/**
      - id: service-trade
        uri: lb://service-trade
        predicates:
          - Path=/*/trade/**
      - id: service-ucenter
        uri: lb://service-ucenter
        predicates:
          - Path=/*/ucenter/**
      - id: service-vod
        uri: lb://service-vod
        predicates:
          - Path=/*/vod/**
      - id: service-statistics
        uri: lb://service-statistics
        predicates:
          - Path=/*/statistics/**
      - id: service-acl
        uri: lb://service-acl
        predicates:
          - Path=/*/acl/**

      discovery:
        locator:
          enabled: true

    nacos:
      discovery:
        server-addr: localhost:8848 # nacos服务地址